In [1]:
import pandas as pd

# Создаем DataFrame из Таблицы 1
data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'Имя': ['Иван', 'Ольга', 'Алексей', 'Мария', 'Сергей', 'Анна', 'Дмитрий', 'Елена', 'Виктор', 'Алиса', 
           'Павел', 'Светлана', 'Роман', 'Татьяна', 'Николай', 'Валерия', 'Григорий', 'Юлия', 'Степан', 'Василиса'],
    'Возраст': [25, 30, 40, 35, 28, 32, 45, 29, 31, 27, 33, 26, 42, 37, 39, 24, 50, 45, 41, 38],
    'Должность': ['Инженер', 'Аналитик', 'Менеджер', 'Программист', 'Специалист', 'Разработчик', 'HR', 
                 'Маркетолог', 'Юрист', 'Дизайнер', 'Администратор', 'Тестировщик', 'Финансист', 'Редактор', 
                 'Логист', 'SEO-специалист', 'Бухгалтер', 'Директор', 'Экономист', 'Проект-менеджер'],
    'Отдел': ['IT', 'Маркетинг', 'Продажи', 'IT', 'HR', 'IT', 'HR', 'Маркетинг', 'Юридический', 'Дизайн', 
             'Администрация', 'Тестирование', 'Финансы', 'Редакция', 'Логистика', 'SEO', 'Бухгалтерия', 
             'Финансы', 'Экономика', 'Продажи'],
    'Зарплата': [60000, 75000, 90000, 80000, 50000, 85000, 48000, 70000, 95000, 62000, 55000, 67000, 
                105000, 72000, 75000, 64000, 110000, 150000, 98000, 88000],
    'Стаж работы': [2, 5, 15, 7, 3, 6, 12, 4, 10, 5, 7, 2, 20, 9, 11, 3, 25, 20, 14, 8]
}

df = pd.DataFrame(data)

# 1. Получение информации о сотруднике с ID = 5 с помощью .loc[]
employee_5 = df.loc[df['ID'] == 5]
print("1. Сотрудник с ID = 5:")
print(employee_5)

# 2. Возраст третьего сотрудника в таблице с .iloc[]
# (индексация начинается с 0, поэтому третий сотрудник имеет индекс 2)
age_3rd = df.iloc[2]['Возраст']
print("\n2. Возраст третьего сотрудника:", age_3rd)

# 3. Название отдела для сотрудника "Мария" с .at[]
# Сначала находим индекс строки с именем "Мария"
maria_index = df[df['Имя'] == 'Мария'].index[0]
department_maria = df.at[maria_index, 'Отдел']
print("\n3. Отдел сотрудника Мария:", department_maria)

# 4. Зарплата сотрудника в четвертой строке и пятом столбце с .iat[]
# (индексация начинается с 0: строка 3, столбец 4)
salary = df.iat[3, 4]
print("\n4. Зарплата сотрудника в 4 строке и 5 столбце:", salary)

# Объяснение разницы между методами:
print("\nРазница между методами доступа:")
print("""
.loc[] - доступ по меткам (названиям строк и столбцов)
.iloc[] - доступ по числовым индексам (позициям)
.at[] - быстрый доступ к скалярному значению по метке (аналог .loc для одного значения)
.iat[] - быстрый доступ к скалярному значению по индексу (аналог .iloc для одного значения)
""")

1. Сотрудник с ID = 5:
   ID     Имя  Возраст   Должность Отдел  Зарплата  Стаж работы
4   5  Сергей       28  Специалист    HR     50000            3

2. Возраст третьего сотрудника: 40

3. Отдел сотрудника Мария: IT

4. Зарплата сотрудника в 4 строке и 5 столбце: IT

Разница между методами доступа:

.loc[] - доступ по меткам (названиям строк и столбцов)
.iloc[] - доступ по числовым индексам (позициям)
.at[] - быстрый доступ к скалярному значению по метке (аналог .loc для одного значения)
.iat[] - быстрый доступ к скалярному значению по индексу (аналог .iloc для одного значения)