In [1]:
import pandas as pd

# Создаем DataFrame из предоставленных данных (объединяем две части таблицы)
data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'Имя': ['Иван', 'Ольга', 'Алексей', 'Мария', 'Сергей', 'Анна', 'Дмитрий', 'Елена', 'Виктор', 'Алиса', 
            'Павел', 'Светлана', 'Роман', 'Татьяна', 'Николай', 'Валерия', 'Григорий', 'Юлия', 'Степан', 'Василиса'],
    'Возраст': [34, 27, 45, 38, 29, 50, 31, 40, 28, 33, 46, 37, 41, 25, 39, 42, 49, 50, 30, 35],
    'Город': ['Москва', 'Санкт-Петербург', 'Казань', 'Новосибирск', 'Екатеринбург', 'Воронеж', 'Челябинск', 
              'Краснодар', 'Ростов-на-Дону', 'Уфа', 'Омск', 'Пермь', 'Тюмень', 'Саратов', 'Самара', 
              'Волгоград', 'Барнаул', 'Иркутск', 'Хабаровск', 'Томск'],
    'Баланс на счете': [120000, 80000, 150000, 200000, 95000, 300000, 140000, 175000, 110000, 98000, 
                        250000, 210000, 135000, 155000, 125000, 180000, 275000, 320000, 105000, 90000],
    'Кредитная история': ['Хорошая', 'Средняя', 'Плохая', 'Хорошая', 'Средняя', 'Отличная', 'Средняя', 
                          'Хорошая', 'Плохая', 'Средняя', 'Хорошая', 'Отличная', 'Средняя', 'Хорошая', 
                          'Средняя', 'Плохая', 'Отличная', 'Хорошая', 'Средняя', 'Плохая']
}

df = pd.DataFrame(data)

# 1. Клиенты из Москвы или Санкт-Петербурга (используем isin)
filter1 = df[df['Город'].isin(['Москва', 'Санкт-Петербург'])]
print("1. Клиенты из Москвы или Санкт-Петербурга:")
print(filter1)

# 2. Клиенты с балансом от 100000 до 250000 (используем between)
filter2 = df[df['Баланс на счете'].between(100000, 250000)]
print("\n2. Клиенты с балансом от 100000 до 250000:")
print(filter2)

# 3. Клиенты с хорошей кредитной историей и балансом > 150000 (используем query)
filter3 = df.query("`Кредитная история` == 'Хорошая' and `Баланс на счете` > 150000")
print("\n3. Клиенты с хорошей кредитной историей и балансом > 150000:")
print(filter3)

1. Клиенты из Москвы или Санкт-Петербурга:
   ID    Имя  Возраст            Город  Баланс на счете Кредитная история
0   1   Иван       34           Москва           120000           Хорошая
1   2  Ольга       27  Санкт-Петербург            80000           Средняя

2. Клиенты с балансом от 100000 до 250000:
    ID       Имя  Возраст           Город  Баланс на счете Кредитная история
0    1      Иван       34          Москва           120000           Хорошая
2    3   Алексей       45          Казань           150000            Плохая
3    4     Мария       38     Новосибирск           200000           Хорошая
6    7   Дмитрий       31       Челябинск           140000           Средняя
7    8     Елена       40       Краснодар           175000           Хорошая
8    9    Виктор       28  Ростов-на-Дону           110000            Плохая
10  11     Павел       46            Омск           250000           Хорошая
11  12  Светлана       37           Пермь           210000          Отличная
12  13     Роман       41          Тюмень           135000           Средняя
13  14   Татьяна       25         Саратов           155000           Хорошая
14  15   Николай       39          Самара           125000           Средняя
15  16   Валерия       42       Волгоград           180000            Плохая
18  19    Степан       30       Хабаровск           105000           Средняя

3. Клиенты с хорошей кредитной историей и балансом > 150000:
    ID      Имя  Возраст        Город  Баланс на счете Кредитная история
3    4    Мария       38  Новосибирск           200000           Хорошая
7    8    Елена       40    Краснодар           175000           Хорошая
10  11    Павел       46         Омск           250000           Хорошая
13  14  Татьяна       25      Саратов           155000           Хорошая
17  18     Юлия       50      Иркутск           320000           Хорошая